version: '2'
services:
    elasticmicromysql-app:
        image: elasticmicromysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://elasticmicromysql-mysql:3306/elasticmicromysql?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticmicromysql-elasticsearch:9300
    elasticmicromysql-mysql:
        extends:
            file: mysql.yml
            service: elasticmicromysql-mysql
    elasticmicromysql-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: elasticmicromysql-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
